5. 다섯번째 실습 - 기본연산


In [ ]:
import numpy as np

# 샘플 데이터 생성
a = np.arange(1,10).reshape(3,3) 
# 원래 1~9까지의 1차원 배열을 (3,3)의 2 차원으로 reshape 해서 출력 
print(a)

print()

b = np.arange(9,0,-1).reshape(3,3)
# 여기도 마찬가지로 reshape
# 중요한 점은 둘다 원본, 사본 -> data : 9 로 동일
print(b)

print()

# 연산
c = a+b
print("+ 사용:",c)
# 또는
print("add 사용:",np.add(a,b))

print()

print("/사용:",a/b)
print("divide 사용:",np.divide(a,b))

print()

# 비교 연산 - 모든 배열의 요소별로 T/F 가 출력된다.
print(a>b)
print(a != b)

print()

import time

# python 과 numpy 의 계산속도 비교 
python = range(10000000)
start = time.time()
for i in python:
  i +1 
end = time.time() 
print("python 걸린시간:",(end-start)*1000 )

print()

numpy = np.arange(10000000)
_start = time.time()
numpy +1
_end = time.time()
print("numpy 걸린시간:", (_end-_start)*1000)

# python > numpy : 즉 고차원의 많은 데이터의 계산도 효율적으로 가능하다! 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

+ 사용: [[10 10 10]
 [10 10 10]
 [10 10 10]]
add 사용: [[10 10 10]
 [10 10 10]
 [10 10 10]]

/사용: [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
divide 사용: [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

[[False False False]
 [False False  True]
 [ True  True  True]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]

python 걸린시간: 855.8552265167236

numpy 걸린시간: 33.66374969482422


6. 여섯번째 실습 - 집계 함수

In [ ]:
import numpy as np


#샘플 데이터 생성 
sample = np.arange(1,10).reshape(3,3)
print(sample)
print()


# axis = None 일때 (행,열 따지지 않을 때)
print("sum",sample.sum()) # 모든 요소의 합
print("mead",sample.mean()) # 모든 요소의 합 / 9
print("std",sample.std()) # 표준편차
print("max",sample.max()) # 모든 요수 중의 큰값
print("min",sample.min()) # 모든 요수 중의 작은값 


print()


# axis = 0 일때 (즉,열만 판단할때 )
print("sum",sample.sum(axis=0)) # 각각 열의  합
print("mead",sample.mean(axis=0)) # 각각 열의 합 / 9
print("std",sample.std(axis=0)) # 표준편차
print("max",sample.max(axis=0)) #각 열 중에 가장  큰값
print("min",sample.min(axis=0)) #각 열 중에 가장 작은값

print()

# axis = 1 일때 (행끼리 판단할 때)
print("sum",sample.sum(axis=1)) # 각 행의 합
print("mead",sample.mean(axis=1)) # 각 행의 합 / 9
print("std",sample.std(axis=1)) # 표준편차
print("max",sample.max(axis=1)) # 각 행 중의 큰값
print("min",sample.min(axis=1)) # 각 행 중의 작은값 


[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum 45
mead 5.0
std 2.581988897471611
max 9
min 1

sum [12 15 18]
mead [4. 5. 6.]
std [2.44948974 2.44948974 2.44948974]
max [7 8 9]
min [1 2 3]

sum [ 6 15 24]
mead [2. 5. 8.]
std [0.81649658 0.81649658 0.81649658]
max [3 6 9]
min [1 4 7]


7 일곱번째 실습 - 데이터 조회를 위한 인덱싱

In [ ]:
import numpy as np

# sample 샘플 데이터 생성
sample = np.arange(5,15)
print(sample)
print("sample[3]:",sample[3])
sample[3]=0
print("sample[3]:",sample[3])

print()

# 2차원 샘플데이터 생성 
data = np.arange(16).reshape((4,4))
print(data)
print("data[2,3]:",data[2,3])
data[2,3]=0
print("data[2,3]:",data[2,3])

print()

# 3차원 샘플데이터 생성
arr = np.arange(16).reshape(4,2,2) #층:4 개 열:2 ,행:2
print(arr)
print("arr[1,1,1]:",arr[1,1,1]) # 1층, 행,열 -1 인 값 : 7
print("arr[2,1,0]:",arr[2,1,0]) # 8
print("arr[3,1,1]:",arr[3,1,1])   # 

[ 5  6  7  8  9 10 11 12 13 14]
sample[3]: 8
sample[3]: 0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
data[2,3]: 11
data[2,3]: 0

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
arr[1,1,1]: 7
arr[2,1,0]: 10
arr[3,1,1]: 15


8 여덟번째 실습-데이터 조회를 위한 슬라이싱


In [ ]:
import numpy as np

# 1차원 샘플 데이터 생성 
data = np.arange(1,15)
print(data)

# 슬라이싱 실습 - python 과 동일하게 이루어짐 - 1차원에서만 
print("1차원 슬라이싱")
print(data[2:5]) #2~4 자리의 수 ..

print(data[:5])  #1~4 자리의 수 
print(data[7:]) # 7~전체
print(data[2:-1]) # 2부터 -1(마지막자리) 의 수까지  
print(data[:]) # 전체 data 출력

print()

# 2차원 데이터 출력 - 행,열 고려해서 슬라이싱
# 3차원 데이터 출력 - 행,열, 축 고려해서 슬라이싱! 
data = np.arange(1,17).reshape(4,4)
print(data)
print("2차원 슬라이싱") #행& 축의 정보 모두 써워야 한다
print(data[1:3, 1:3]) #행1~2 부터, 열 1~2 까지 공통된 부분 출력 
print()
print(data[:3, 0:1]) # 행 처음~2, 열 0 
print()
print(data[3:,:]) # 행 3~전체 , 열 전체
print(data[:,2])  # 행 전체, 열 2번째
print(data[:, :])  # 행,열 전체 

print()

# 데이터 슬라이싱 - 역방향 방법 - Negative index 
print(data[:,1:-1]) # 행-전체, 열- 1부터 (-1) 의 값 전까지  
print(data[:,-1]) # 행전체, 열 - -1 만  


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1차원 슬라이싱
[3 4 5]
[1 2 3 4 5]
[ 8  9 10 11 12 13 14]
[ 3  4  5  6  7  8  9 10 11 12 13]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2차원 슬라이싱
[[ 6  7]
 [10 11]]

[[1]
 [5]
 [9]]

[[13 14 15 16]]
[ 3  7 11 15]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[ 4  8 12 16]


9. 아홉번째 실습 - 데이터 정렬

In [ ]:
import numpy as np

# 샘플 데이터 생성
sample = np.array([2,5,8,1])
print("or",sample)

# 정렬 - 원본데이터를 정렬해도 사본으로 저장되어 출력 됨 즉, 원본 변경 안됨 - 오름차순 정리만 가능
result = np.sort(sample)
print("re",result) 
print("or",sample)
three = sample.sort()
print("re1",sample)
print("re",three)

print()

# 내림차순과 역출력의 차의
#1. 역출력 - 정렬함수 안에서 negative func 사용
print("ascending",sample[::-1])
# 내림차순 - 1. sort 2. negative func 사용
arr = np.sort(sample)
result = arr[::-1]
print("as2",result)

print()

# 2차원, 3차원 정렬 방법 - axis 이용
# 샘플데이터 생성
sample = np.array([[9,11],[5,1]]) # 2차원
print(sample)

# 2차원 배열 정렬 - 중심 축을 정해야 한다 ex> axis=0 또는  axis=1
result = np.sort(sample,axis=0)
print(result) #axis=0 은 열끼리 정렬해서 나옴

# axis=1 사용
result = np.sort(sample, axis=1)
print(result) # 이떄는 행끼리 정렬되어 나옴

# argsort() 함수 이용해서 인덱스 값만 반환

name = np.array(['kim','lee','park','cho'])
score = np.array([78,32,100,96])

sort_list = np.argsort(score) #score 를 정렬 32,76,96,100 -> 1,0,3,2로 index 정렬
print(sort_list)

# 정렬된 것을가지고 이름과 매치해서 이름을 순위대로 출력하는 방법
print(name[sort_list]) #1,0,3,2 -> 0,1,2,3->lee,kim,cho,park


or [2 5 8 1]
re [1 2 5 8]
or [2 5 8 1]
re1 [1 2 5 8]
re None

ascending [8 5 2 1]
as2 [8 5 2 1]

[[ 9 11]
 [ 5  1]]
[[ 5  1]
 [ 9 11]]
[[ 9 11]
 [ 1  5]]
[1 0 3 2]
['lee' 'kim' 'cho' 'park']
