1. Numpy (code_presso)
첫번째  실습 - numpy 의 이해



In [ ]:
import numpy as np # numpy 의 일반적인 별칭으로 np 를 많이 씀
print(np.__version__)

# ndarray 의 주요 속성
# shape, size, dtype , ndim 으로 확인 가능 


# 1차원 배열 
data = [10,20,30]
arr= np.array(data)
print("1차원 행렬 :",data)
print("type: ",type(arr))
print("1. shape={} ,size={}, dtype={}, ndim={}".format(arr.shape,arr.size,arr.dtype,arr.ndim))
# ndim =1 에 따라 axis=0 축밖에 없으며 그 축은 data 값이 3 이다.

print()

# 2차원 배열
data = [[1,2,3], [4,5,6]]
print(data) 
arr= np.array(data, dtype=float)
print(arr)
print("2. shape:{},size={},dtype={},ndim={}".format(arr.shape, arr.size, arr.dtype,arr.ndim))
# ndim=2 에 따라 axis=0, axis=1 두개가 있는데 차례대로 2,3 의 date 값을 가지고 있다

print()

# 3차원 배열
data = [[[1, 2, 3],
         [4, 5, 6]],
        [[3, 2, 1],
         [4, 5, 6]]]
arr = np.array(data,dtype=float)
print(arr)
print("3. shape:{},size={},dtype={},ndim={}".format(arr.shape, arr.size, arr.dtype,arr.ndim))
# ndim=3 에 따라 axis=0,1,2 총 3 개가 있는데 차례대로 2,2,3 의 data 값을 가지고 있다 
# 즉 shape 의 값의 결정하는 순서는 axis 가 된다. 


1.19.5
1차원 행렬 : [10, 20, 30]
type:  <class 'numpy.ndarray'>
1. shape=(3,) ,size=3, dtype=int64, ndim=1

[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
2. shape:(2, 3),size=6,dtype=float64,ndim=2

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]
3. shape:(2, 2, 3),size=12,dtype=float64,ndim=3


2. 두번째 실습 - numpy 의 생성


In [ ]:
import numpy as np

# 속성을 알기 위한 함수 생성
def printinfo(arr):
  print(arr)
  print("shape:{},size:{},dtype:{},ndim:{}".format(arr.shape, arr.size,arr.dtype,arr.ndim))

# np.arange() 함수 사용법 - dtype : int 
arr = np.arange(10)
printinfo(arr) 

print()

# np.zeros() 함수 사용법 - dtype : float
arr = np.zeros(5)  # zeros(shape, 생략하면 무조건 (0))
printinfo(arr)

print()

# 두번째 zeros
arr = np.zeros((3,4),dtype=int)  # 2차원 배열, 0 초기화
printinfo(arr)

print()

# np.ones() 함수 사용법 - 1로 초기화 , dtype = float
arr= np.ones(5)
printinfo(arr)
arr = np.ones((3,4))
printinfo(arr)

print()

# np.full() 함수 사용법 - shape대입, 내가 대입한 값으로 초기화
arr= np.full((3,4),128)
printinfo(arr)

print()

#np.empty()
arr = np.empty(3)
print("xx", arr)

# no.ones_like() 함수 사용법 - shape 을 그 전 배열을 따와서 생성, data=1 초기화
data = [[1,2,3], [4,5,6]]
sample =  np.array(data) # 2차원 행렬 데이터 2*3
arr= np.ones_like(sample) # 주의할 점은 data 를 넣는것이 아니라 array 함수로 만든 후에 대입하는것
printinfo(arr)


[0 1 2 3 4 5 6 7 8 9]
shape:(10,),size:10,dtype:int64,ndim:1

[0. 0. 0. 0. 0.]
shape:(5,),size:5,dtype:float64,ndim:1

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape:(3, 4),size:12,dtype:int64,ndim:2

[1. 1. 1. 1. 1.]
shape:(5,),size:5,dtype:float64,ndim:1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape:(3, 4),size:12,dtype:float64,ndim:2

[[128 128 128 128]
 [128 128 128 128]
 [128 128 128 128]]
shape:(3, 4),size:12,dtype:int64,ndim:2

xx [0.75 0.75 0.  ]
[[1 1 1]
 [1 1 1]]
shape:(2, 3),size:6,dtype:int64,ndim:2


3. 세번째 실습 - numpy의 데이터 타입


In [ ]:
import numpy as np
# 데이터 타입 변경 첫번째 - dtype 을 이용해 변환
data= [10,20,30]
com = np.array(data,complex)
st = np.array(data,str)
ori = np.array(data)
print("ori dtype {}, com dtype{} , st type{}".format(ori.dtype , com.dtype, st.dtype))
print(ori,com,st)

print()

# 데이터 타입 변경 두번째 - astype 를 이용해 변환
data = np.arange(1,2,0.2)
print(data)
print("data dtype {}".format(data.dtype))
print()
sample = data.astype(int)
print(sample)
print("sample dtype: {}".format(sample.dtype))

# 원본 - data , float 
# 수정본 - sample, int 
# numpy 자체가 데이터 분석에 많이 쓰이다 보니 원본데이터의 손실을 고려하여
# 형변환시에 원본 데이터는 변화가 없고 형변환을 한 원본의 새로운 데이터를 만들어 
# 출력한다. - 즉, 안전하게 원본을 보호하기 위해서 ! 

ori dtype int64, com dtypecomplex128 , st type<U2
[10 20 30] [10.+0.j 20.+0.j 30.+0.j] ['10' '20' '30']

[1.  1.2 1.4 1.6 1.8]
data dtype float64

[1 1 1 1 1]
sample dtype: int64




4. 네번째 실습 - reshape




In [ ]:
import numpy as np

def printinfo(arr):
  print(arr)
  print("shape:{},size:{},dtype:{},ndim:{}".format(arr.shape,arr.size,arr.dtype,arr.ndim))

# 샘플 데이터
original = np.arange(15)
printinfo(original)
print()

# reshape - 첫번째 방법 np.shape 이용 
#a = np.reshape(original,(3,6))
#Valueerror : cannot reshape array of size 15 into shape(3,6) 라는 에러가 뜨는데 매우 중요!!
# ori= 15 개의 data 가 있지만 a 는 (3,6)=18 개의 date 이므로 원본손실의 우려가 있기 때문에
# error 가 발생하게 된다!
# 즉, reshape 는 바꾸기 전,후 의 data size 가 같아야 가능하다! - 중요!
a = np.reshape(original,(3,5))
printinfo(a)
print()

# 두번째 방법 - -1,n 이용
arr = original.reshape(-1,15) # arr 은 원래 data = 15 개 
                             # -1은 가변적이고 15 개를 만들기 위해 (-1,n) 에 n 값에 수를 대입
                            # ex> 3,5 = 15 이기에 n 에 3과 5 를 각각 대입해보면
                            # 원래 1차원이였던 original 를 2차원인 arr 로변형된것을 알수 있다. 
printinfo(arr)
print()
arr1 = original.reshape(-1,3)
printinfo(arr1)
print()
arr2 = original.reshape(-1,5)
printinfo(arr2)
print()
arr3 = original.reshape(-1,1)
printinfo(arr3)
print()



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape:(15,),size:15,dtype:int64,ndim:1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape:(3, 5),size:15,dtype:int64,ndim:2

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
shape:(1, 15),size:15,dtype:int64,ndim:2

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
shape:(5, 3),size:15,dtype:int64,ndim:2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape:(3, 5),size:15,dtype:int64,ndim:2

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
shape:(15, 1),size:15,dtype:int64,ndim:2



5. 다섯번째 실습 - 기본연산


In [ ]:
import numpy as np

# 샘플 데이터 생성
a = np.arange(1,10).reshape(3,3) 
# 원래 1~9까지의 1차원 배열을 (3,3)의 2 차원으로 reshape 해서 출력 
print(a)

print()

b = np.arange(9,0,-1).reshape(3,3)
# 여기도 마찬가지로 reshape
# 중요한 점은 둘다 원본, 사본 -> data : 9 로 동일
print(b)

print()

# 연산
c = a+b
print("+ 사용:",c)
# 또는
print("add 사용:",np.add(a,b))

print()

print("/사용:",a/b)
print("divide 사용:",np.divide(a,b))

print()

# 비교 연산 - 모든 배열의 요소별로 T/F 가 출력된다.
print(a>b)
print(a != b)

print()

import time

# python 과 numpy 의 계산속도 비교 
python = range(10000000)
start = time.time()
for i in python:
  i +1 
end = time.time() 
print("python 걸린시간:",(end-start)*1000 )

print()

numpy = np.arange(10000000)
_start = time.time()
numpy +1
_end = time.time()
print("numpy 걸린시간:", (_end-_start)*1000)

# python > numpy : 즉 고차원의 많은 데이터의 계산도 효율적으로 가능하다! 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

+ 사용: [[10 10 10]
 [10 10 10]
 [10 10 10]]
add 사용: [[10 10 10]
 [10 10 10]
 [10 10 10]]

/사용: [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
divide 사용: [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

[[False False False]
 [False False  True]
 [ True  True  True]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]

python 걸린시간: 855.8552265167236

numpy 걸린시간: 33.66374969482422


6. 여섯번째 실습 - 집계 함수

In [ ]:
import numpy as np


#샘플 데이터 생성 
sample = np.arange(1,10).reshape(3,3)
print(sample)
print()


# axis = None 일때 (행,열 따지지 않을 때)
print("sum",sample.sum()) # 모든 요소의 합
print("mead",sample.mean()) # 모든 요소의 합 / 9
print("std",sample.std()) # 표준편차
print("max",sample.max()) # 모든 요수 중의 큰값
print("min",sample.min()) # 모든 요수 중의 작은값 


print()


# axis = 0 일때 (즉,열만 판단할때 )
print("sum",sample.sum(axis=0)) # 각각 열의  합
print("mead",sample.mean(axis=0)) # 각각 열의 합 / 9
print("std",sample.std(axis=0)) # 표준편차
print("max",sample.max(axis=0)) #각 열 중에 가장  큰값
print("min",sample.min(axis=0)) #각 열 중에 가장 작은값

print()

# axis = 1 일때 (행끼리 판단할 때)
print("sum",sample.sum(axis=1)) # 각 행의 합
print("mead",sample.mean(axis=1)) # 각 행의 합 / 9
print("std",sample.std(axis=1)) # 표준편차
print("max",sample.max(axis=1)) # 각 행 중의 큰값
print("min",sample.min(axis=1)) # 각 행 중의 작은값 


[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum 45
mead 5.0
std 2.581988897471611
max 9
min 1

sum [12 15 18]
mead [4. 5. 6.]
std [2.44948974 2.44948974 2.44948974]
max [7 8 9]
min [1 2 3]

sum [ 6 15 24]
mead [2. 5. 8.]
std [0.81649658 0.81649658 0.81649658]
max [3 6 9]
min [1 4 7]


7 일곱번째 실습 - 데이터 조회를 위한 인덱싱

In [ ]:
import numpy as np

# sample 샘플 데이터 생성
sample = np.arange(5,15)
print(sample)
print("sample[3]:",sample[3])
sample[3]=0
print("sample[3]:",sample[3])

print()

# 2차원 샘플데이터 생성 
data = np.arange(16).reshape((4,4))
print(data)
print("data[2,3]:",data[2,3])
data[2,3]=0
print("data[2,3]:",data[2,3])

print()

# 3차원 샘플데이터 생성
arr = np.arange(16).reshape(4,2,2) #층:4 개 열:2 ,행:2
print(arr)
print("arr[1,1,1]:",arr[1,1,1]) # 1층, 행,열 -1 인 값 : 7
print("arr[2,1,0]:",arr[2,1,0]) # 8
print("arr[3,1,1]:",arr[3,1,1])   # 

[ 5  6  7  8  9 10 11 12 13 14]
sample[3]: 8
sample[3]: 0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
data[2,3]: 11
data[2,3]: 0

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
arr[1,1,1]: 7
arr[2,1,0]: 10
arr[3,1,1]: 15


8 여덟번째 실습-데이터 조회를 위한 슬라이싱


In [ ]:
import numpy as np

# 1차원 샘플 데이터 생성 
data = np.arange(1,15)
print(data)

# 슬라이싱 실습 - python 과 동일하게 이루어짐 - 1차원에서만 
print("1차원 슬라이싱")
print(data[2:5]) #2~4 자리의 수 ..

print(data[:5])  #1~4 자리의 수 
print(data[7:]) # 7~전체
print(data[2:-1]) # 2부터 -1(마지막자리) 의 수까지  
print(data[:]) # 전체 data 출력

print()

# 2차원 데이터 출력 - 행,열 고려해서 슬라이싱
# 3차원 데이터 출력 - 행,열, 축 고려해서 슬라이싱! 
data = np.arange(1,17).reshape(4,4)
print(data)
print("2차원 슬라이싱") #행& 축의 정보 모두 써워야 한다
print(data[1:3, 1:3]) #행1~2 부터, 열 1~2 까지 공통된 부분 출력 
print()
print(data[:3, 0:1]) # 행 처음~2, 열 0 
print()
print(data[3:,:]) # 행 3~전체 , 열 전체
print(data[:,2])  # 행 전체, 열 2번째
print(data[:, :])  # 행,열 전체 

print()

# 데이터 슬라이싱 - 역방향 방법 - Negative index 
print(data[:,1:-1]) # 행-전체, 열- 1부터 (-1) 의 값 전까지  
print(data[:,-1]) # 행전체, 열 - -1 만  


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1차원 슬라이싱
[3 4 5]
[1 2 3 4 5]
[ 8  9 10 11 12 13 14]
[ 3  4  5  6  7  8  9 10 11 12 13]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2차원 슬라이싱
[[ 6  7]
 [10 11]]

[[1]
 [5]
 [9]]

[[13 14 15 16]]
[ 3  7 11 15]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[ 4  8 12 16]


9. 아홉번째 실습 - 데이터 정렬

In [ ]:
import numpy as np

# 샘플 데이터 생성
sample = np.array([2,5,8,1])
print("or",sample)

# 정렬 - 원본데이터를 정렬해도 사본으로 저장되어 출력 됨 즉, 원본 변경 안됨 - 오름차순 정리만 가능
result = np.sort(sample)
print("re",result) 
print("or",sample)
three = sample.sort()
print("re1",sample)
print("re",three)

print()

# 내림차순과 역출력의 차의
#1. 역출력 - 정렬함수 안에서 negative func 사용
print("ascending",sample[::-1])
# 내림차순 - 1. sort 2. negative func 사용
arr = np.sort(sample)
result = arr[::-1]
print("as2",result)

print()

# 2차원, 3차원 정렬 방법 - axis 이용
# 샘플데이터 생성
sample = np.array([[9,11],[5,1]]) # 2차원
print(sample)

# 2차원 배열 정렬 - 중심 축을 정해야 한다 ex> axis=0 또는  axis=1
result = np.sort(sample,axis=0)
print(result) #axis=0 은 열끼리 정렬해서 나옴

# axis=1 사용
result = np.sort(sample, axis=1)
print(result) # 이떄는 행끼리 정렬되어 나옴

# argsort() 함수 이용해서 인덱스 값만 반환

name = np.array(['kim','lee','park','cho'])
score = np.array([78,32,100,96])

sort_list = np.argsort(score) #score 를 정렬 32,76,96,100 -> 1,0,3,2로 index 정렬
print(sort_list)

# 정렬된 것을가지고 이름과 매치해서 이름을 순위대로 출력하는 방법
print(name[sort_list]) #1,0,3,2 -> 0,1,2,3->lee,kim,cho,park


or [2 5 8 1]
re [1 2 5 8]
or [2 5 8 1]
re1 [1 2 5 8]
re None

ascending [8 5 2 1]
as2 [8 5 2 1]

[[ 9 11]
 [ 5  1]]
[[ 5  1]
 [ 9 11]]
[[ 9 11]
 [ 1  5]]
[1 0 3 2]
['lee' 'kim' 'cho' 'park']
