1. Numpy
첫번째  실습 - numpy 의 이해



In [ ]:
import numpy as np # numpy 의 일반적인 별칭으로 np 를 많이 씀
print(np.__version__)

# ndarray 의 주요 속성
# shape, size, dtype , ndim 으로 확인 가능 


# 1차원 배열 
data = [10,20,30]
arr= np.array(data)
print("1차원 행렬 :",data)
print("type: ",type(arr))
print("1. shape={} ,size={}, dtype={}, ndim={}".format(arr.shape,arr.size,arr.dtype,arr.ndim))
# ndim =1 에 따라 axis=0 축밖에 없으며 그 축은 data 값이 3 이다.

print()

# 2차원 배열
data = [[1,2,3], [4,5,6]]
print(data) 
arr= np.array(data, dtype=float)
print(arr)
print("2. shape:{},size={},dtype={},ndim={}".format(arr.shape, arr.size, arr.dtype,arr.ndim))
# ndim=2 에 따라 axis=0, axis=1 두개가 있는데 차례대로 2,3 의 date 값을 가지고 있다

print()

# 3차원 배열
data = [[[1, 2, 3],
         [4, 5, 6]],
        [[3, 2, 1],
         [4, 5, 6]]]
arr = np.array(data,dtype=float)
print(arr)
print("3. shape:{},size={},dtype={},ndim={}".format(arr.shape, arr.size, arr.dtype,arr.ndim))
# ndim=3 에 따라 axis=0,1,2 총 3 개가 있는데 차례대로 2,2,3 의 data 값을 가지고 있다 
# 즉 shape 의 값의 결정하는 순서는 axis 가 된다. 


1.19.5
1차원 행렬 : [10, 20, 30]
type:  <class 'numpy.ndarray'>
1. shape=(3,) ,size=3, dtype=int64, ndim=1

[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
2. shape:(2, 3),size=6,dtype=float64,ndim=2

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]
3. shape:(2, 2, 3),size=12,dtype=float64,ndim=3


2. 두번째 실습 - numpy 의 생성


In [ ]:
import numpy as np

# 속성을 알기 위한 함수 생성
def printinfo(arr):
  print(arr)
  print("shape:{},size:{},dtype:{},ndim:{}".format(arr.shape, arr.size,arr.dtype,arr.ndim))

# np.arange() 함수 사용법 - dtype : int 
arr = np.arange(10)
printinfo(arr) 

print()

# np.zeros() 함수 사용법 - dtype : float
arr = np.zeros(5)  # zeros(shape, 생략하면 무조건 (0))
printinfo(arr)

print()

# 두번째 zeros
arr = np.zeros((3,4),dtype=int)  # 2차원 배열, 0 초기화
printinfo(arr)

print()

# np.ones() 함수 사용법 - 1로 초기화 , dtype = float
arr= np.ones(5)
printinfo(arr)
arr = np.ones((3,4))
printinfo(arr)

print()

# np.full() 함수 사용법 - shape대입, 내가 대입한 값으로 초기화
arr= np.full((3,4),128)
printinfo(arr)

print()

#np.empty()
arr = np.empty(3)
print("xx", arr)

# no.ones_like() 함수 사용법 - shape 을 그 전 배열을 따와서 생성, data=1 초기화
data = [[1,2,3], [4,5,6]]
sample =  np.array(data) # 2차원 행렬 데이터 2*3
arr= np.ones_like(sample) # 주의할 점은 data 를 넣는것이 아니라 array 함수로 만든 후에 대입하는것
printinfo(arr)


[0 1 2 3 4 5 6 7 8 9]
shape:(10,),size:10,dtype:int64,ndim:1

[0. 0. 0. 0. 0.]
shape:(5,),size:5,dtype:float64,ndim:1

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape:(3, 4),size:12,dtype:int64,ndim:2

[1. 1. 1. 1. 1.]
shape:(5,),size:5,dtype:float64,ndim:1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape:(3, 4),size:12,dtype:float64,ndim:2

[[128 128 128 128]
 [128 128 128 128]
 [128 128 128 128]]
shape:(3, 4),size:12,dtype:int64,ndim:2

xx [0.75 0.75 0.  ]
[[1 1 1]
 [1 1 1]]
shape:(2, 3),size:6,dtype:int64,ndim:2


3. 세번째 실습 - numpy의 데이터 타입


In [ ]:
import numpy as np
# 데이터 타입 변경 첫번째 - dtype 을 이용해 변환
data= [10,20,30]
com = np.array(data,complex)
st = np.array(data,str)
ori = np.array(data)
print("ori dtype {}, com dtype{} , st type{}".format(ori.dtype , com.dtype, st.dtype))
print(ori,com,st)

print()

# 데이터 타입 변경 두번째 - astype 를 이용해 변환
data = np.arange(1,2,0.2)
print(data)
print("data dtype {}".format(data.dtype))
print()
sample = data.astype(int)
print(sample)
print("sample dtype: {}".format(sample.dtype))

# 원본 - data , float 
# 수정본 - sample, int 
# numpy 자체가 데이터 분석에 많이 쓰이다 보니 원본데이터의 손실을 고려하여
# 형변환시에 원본 데이터는 변화가 없고 형변환을 한 원본의 새로운 데이터를 만들어 
# 출력한다. - 즉, 안전하게 원본을 보호하기 위해서 ! 

ori dtype int64, com dtypecomplex128 , st type<U2
[10 20 30] [10.+0.j 20.+0.j 30.+0.j] ['10' '20' '30']

[1.  1.2 1.4 1.6 1.8]
data dtype float64

[1 1 1 1 1]
sample dtype: int64




4. 네번째 실습 - reshape




In [ ]:
import numpy as np

def printinfo(arr):
  print(arr)
  print("shape:{},size:{},dtype:{},ndim:{}".format(arr.shape,arr.size,arr.dtype,arr.ndim))

# 샘플 데이터
original = np.arange(15)
printinfo(original)
print()

# reshape - 첫번째 방법 np.shape 이용 
#a = np.reshape(original,(3,6))
#Valueerror : cannot reshape array of size 15 into shape(3,6) 라는 에러가 뜨는데 매우 중요!!
# ori= 15 개의 data 가 있지만 a 는 (3,6)=18 개의 date 이므로 원본손실의 우려가 있기 때문에
# error 가 발생하게 된다!
# 즉, reshape 는 바꾸기 전,후 의 data size 가 같아야 가능하다! - 중요!
a = np.reshape(original,(3,5))
printinfo(a)
print()

# 두번째 방법 - -1,n 이용
arr = original.reshape(-1,15) # arr 은 원래 data = 15 개 
                             # -1은 가변적이고 15 개를 만들기 위해 (-1,n) 에 n 값에 수를 대입
                            # ex> 3,5 = 15 이기에 n 에 3과 5 를 각각 대입해보면
                            # 원래 1차원이였던 original 를 2차원인 arr 로변형된것을 알수 있다. 
printinfo(arr)
print()
arr1 = original.reshape(-1,3)
printinfo(arr1)
print()
arr2 = original.reshape(-1,5)
printinfo(arr2)
print()
arr3 = original.reshape(-1,1)
printinfo(arr3)
print()



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape:(15,),size:15,dtype:int64,ndim:1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape:(3, 5),size:15,dtype:int64,ndim:2

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
shape:(1, 15),size:15,dtype:int64,ndim:2

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
shape:(5, 3),size:15,dtype:int64,ndim:2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape:(3, 5),size:15,dtype:int64,ndim:2

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
shape:(15, 1),size:15,dtype:int64,ndim:2

